-- Who's to Say Studio auth and authorization foundation (draft).
-- Review and test in a non-production Supabase project before applying.
-- Google OAuth authenticates users through Supabase Auth; these tables authorize access.
-- This migration is additive and does not alter the existing albums/photos schema.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is
  'Studio-facing profile for an authenticated Supabase user; never grants authorization by itself.';

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  registry_id text not null unique check (registry_id ~ '^participant-[a-z0-9]+(?:-[a-z0-9]+)*$'),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  display_name text not null,
  status text not null default 'draft' check (status in ('draft', 'active', 'inactive', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.participants is
  'Database participant identity mapped to content/participants registry_id; does not create a public route.';

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('superadmin', 'staff')),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  unique (user_id, role)
);

comment on table public.user_roles is
  'Small set of global Studio roles. Participant owner/contributor access belongs in participant_user_access.';

create table if not exists public.participant_user_access (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  access_role text not null check (access_role in ('participant_owner', 'participant_admin', 'contributor')),
  can_edit_page boolean not null default false,
  can_edit_brand_kit boolean not null default false,
  can_select_media boolean not null default false,
  can_edit_services boolean not null default false,
  can_submit_review boolean not null default false,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  unique (participant_id, user_id, access_role),
  check (expires_at is null or expires_at > starts_at)
);

comment on table public.participant_user_access is
  'Participant-scoped authorization. OAuth identity or email alone never creates one of these rows.';

create table if not exists public.participant_album_access (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  album_id uuid not null,
  access_level text not null default 'select' check (access_level in ('view', 'select', 'manage')),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  unique (participant_id, album_id)
);

comment on table public.participant_album_access is
  'Participant-to-Media-Hub album assignment. album_id intentionally has no new FK in this draft so existing album tables are untouched.';

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  participant_id uuid references public.participants(id) on delete set null,
  event_type text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

comment on table public.audit_events is
  'Append-only audit target for trusted Studio server actions. No client insert policy is granted in this draft.';

create index if not exists participant_user_access_user_idx
  on public.participant_user_access(user_id, participant_id);
create index if not exists participant_album_access_participant_idx
  on public.participant_album_access(participant_id, album_id);
create index if not exists audit_events_participant_time_idx
  on public.audit_events(participant_id, occurred_at desc);

alter table public.profiles enable row level security;
alter table public.participants enable row level security;
alter table public.user_roles enable row level security;
alter table public.participant_user_access enable row level security;
alter table public.participant_album_access enable row level security;
alter table public.audit_events enable row level security;

-- SECURITY DEFINER helpers centralize authorization checks. Keep execute access
-- limited to authenticated users and do not accept a user ID from the client.
create or replace function public.is_studio_superadmin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'superadmin'
  );
$$;

create or replace function public.has_participant_access(target_participant_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_studio_superadmin() or exists (
    select 1
    from public.participant_user_access access
    where access.participant_id = target_participant_id
      and access.user_id = auth.uid()
      and access.revoked_at is null
      and access.starts_at <= now()
      and (access.expires_at is null or access.expires_at > now())
  );
$$;

revoke all on function public.is_studio_superadmin() from public;
revoke all on function public.has_participant_access(uuid) from public;
grant execute on function public.is_studio_superadmin() to authenticated;
grant execute on function public.has_participant_access(uuid) to authenticated;

-- Starter policies are intentionally conservative. There are no anonymous
-- policies and no client policies that create roles, access, or audit events.
create policy "profiles_read_own"
  on public.profiles for select to authenticated
  using (user_id = auth.uid() or public.is_studio_superadmin());

create policy "profiles_insert_own"
  on public.profiles for insert to authenticated
  with check (user_id = auth.uid());

create policy "profiles_update_own"
  on public.profiles for update to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "participants_read_assigned"
  on public.participants for select to authenticated
  using (public.has_participant_access(id));

create policy "participants_superadmin_write"
  on public.participants for all to authenticated
  using (public.is_studio_superadmin())
  with check (public.is_studio_superadmin());

create policy "user_roles_read_own"
  on public.user_roles for select to authenticated
  using (user_id = auth.uid() or public.is_studio_superadmin());

create policy "user_roles_superadmin_write"
  on public.user_roles for all to authenticated
  using (public.is_studio_superadmin())
  with check (public.is_studio_superadmin());

create policy "participant_access_read_own"
  on public.participant_user_access for select to authenticated
  using (user_id = auth.uid() or public.is_studio_superadmin());

create policy "participant_access_superadmin_write"
  on public.participant_user_access for all to authenticated
  using (public.is_studio_superadmin())
  with check (public.is_studio_superadmin());

create policy "album_access_read_assigned"
  on public.participant_album_access for select to authenticated
  using (public.has_participant_access(participant_id));

create policy "album_access_superadmin_write"
  on public.participant_album_access for all to authenticated
  using (public.is_studio_superadmin())
  with check (public.is_studio_superadmin());

create policy "audit_events_read_authorized"
  on public.audit_events for select to authenticated
  using (
    public.is_studio_superadmin()
    or (participant_id is not null and public.has_participant_access(participant_id))
  );

-- Intentionally omitted in this phase:
-- - contact/social profile tables or fields
-- - review_requests and publish_events (required before publishing is enabled)
-- - participant page or Brand Kit draft tables
-- - policies modifying existing albums/photos
-- - automatic authorization based on Google/email identity
